#!/bin/perl
use utf8;
if (/\<title\>Currently/) {
    chomp;
    /\<title\>Currently: (.*)?C\<\/title\>/;
    my@ values = split(":", $1);
    if ($values[0] eq "Sunny" || $values[0] eq "Mostly Sunny" || $values[0] eq "Partly Sunny" || $values[0] eq "Intermittent Clouds" || $values[0] eq "Hazy Sunshine" || $values[0] eq "Hazy Sunshine" || $values[0] eq "Hot") {
        my $sun = "";
        binmode(STDOUT, ":utf8");
        print "$sun";
    }
    if ($values[0] eq "Mostly Cloudy" || $values[0] eq "Cloudy" || $values[0] eq "Dreary (Overcast)" || $values[0] eq "Fog") {
        my $cloud = "";
        binmode(STDOUT, ":utf8");
        print "$cloud";
    }
    if ($values[0] eq "Showers" || $values[0] eq "Mostly Cloudy W/ Showers" || $values[0] eq "Partly Sunny W/ Showers" || $values[0] eq "T-Storms" || $values[0] eq "Mostly Cloudy W/ T-Storms" || $values[0] eq "Partly Sunny W/ T-Storms" || $values[0] eq "Rain") {
        my $rain = "";
        binmode(STDOUT, ":utf8");
        print "$rain";
    }
    if ($values[0] eq "Windy") {
        my $wind = "";
        binmode(STDOUT, ":utf8");
        print "$wind";
    }
    if ($values[0] eq "Flurries" || $values[0] eq "Mostly Cloudy W/ Flurries" || $values[0] eq "Partly Sunny W/ Flurries" || $values[0] eq "Snow" || $values[0] eq "Mostly Cloudy W/ Snow" || $values[0] eq "Ice" || $values[0] eq "Sleet" || $values[0] eq "Freezing Rain" || $values[0] eq "Rain and Snow" || $values[0] eq "Cold") {
        my $snow = "";
        binmode(STDOUT, ":utf8");
        print "$snow";
    }
    if ($values[0] eq "Hazy Moonlight") {
        my $night = "";
        binmode(STDOUT, ":utf8");
        print "$night";
    }
		print "$values[1]";
		my $degsym = "°C";
    binmode(STDOUT, ":utf8");
		print "$degsym";
}

